# Generated by Django 3.2.9 on 2021-12-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(db_column='cName', max_length=50)),
                ('cStatus', models.IntegerField(db_column='cStatus')),
                ('cCreate_at', models.DateTimeField(db_column='cCreate_at')),
                ('cUpdate_at', models.DateTimeField(db_column='cUpdate_at')),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dName', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dPrice', models.CharField(max_length=250)),
                ('dEffect', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dUsage', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dType', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dSale', models.CharField(max_length=250)),
                ('dNum', models.CharField(max_length=250)),
                ('dStatus', models.IntegerField()),
                ('dCreate_at', models.DateTimeField()),
                ('dUpdate_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Drug',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=50)),
                ('password_salt', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Employee',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uName', models.CharField(db_column='uName', max_length=50)),
                ('uPassword_hash', models.CharField(db_column='uPassword_hash', max_length=50)),
                ('uPassword_salt', models.CharField(db_column='uPassword_salt', max_length=50)),
                ('uTel', models.CharField(db_column='uTel', max_length=50)),
                ('uType', models.CharField(db_column='uType', max_length=50)),
                ('uGender', models.CharField(db_column='uGender', max_length=1)),
                ('uBirth', models.DateTimeField(db_column='uBirth')),
                ('uAddress', models.CharField(db_column='uAddress', max_length=100)),
                ('uCreate_at', models.DateTimeField(default='NUll')),
                ('uUpdate_at', models.DateTimeField(default='NULL')),
            ],
            options={
                'db_table': 'Member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TotalDrug',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dName', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dPrice', models.CharField(max_length=250)),
                ('dEffect', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('dUsage', models.CharField(db_collation='gbk_chinese_ci', max_length=250)),
                ('picture', models.CharField(default='null', max_length=250)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'total_drug',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='emp_Drug',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('edCreate_at', models.DateTimeField(default='NUll')),
                ('edUpdate_at', models.DateTimeField(default='NULL')),
                ('eName', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.employee')),
                ('edName', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.drug')),
            ],
            options={
                'db_table': 'emp_Drug',
                'managed': True,
            },
        ),
    ]
