# Generated by Django 3.2.9 on 2021-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apothecary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aid', models.CharField(db_column='aID', max_length=10)),
                ('aname', models.CharField(db_column='aName', max_length=10)),
                ('apassword', models.CharField(db_column='aPassword', max_length=18)),
                ('agender', models.CharField(db_column='aGender', max_length=8)),
                ('atel', models.CharField(db_column='aTel', max_length=11)),
                ('afield', models.CharField(db_column='aField', max_length=200)),
                ('atimetable', models.CharField(db_column='aTimetable', max_length=50)),
                ('ahospital', models.CharField(db_column='aHospital', max_length=20)),
                ('astate', models.CharField(db_column='aState', max_length=20)),
            ],
            options={
                'db_table': 'Apothecary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(db_column='cName', max_length=50)),
                ('cStatus', models.IntegerField(db_column='cStatus')),
                ('cCreate_at', models.DateTimeField(db_column='cCreate_at')),
                ('cUpdate_at', models.DateTimeField(db_column='cUpdate_at')),
            ],
            options={
                'db_table': 'mcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('uId', models.BigAutoField(primary_key=True, serialize=False)),
                ('uPassword', models.CharField(db_column='uPassword', max_length=10)),
                ('uName', models.CharField(db_column='uName', max_length=10)),
                ('uType', models.CharField(db_column='uType', max_length=10)),
                ('uGender', models.CharField(db_column='uGender', max_length=6)),
                ('uBirth', models.CharField(db_column='uBirth', max_length=8)),
                ('uTel', models.CharField(db_column='uTel', max_length=11)),
                ('uAddress', models.CharField(db_column='uAddress', max_length=30)),
            ],
            options={
                'db_table': 'mywebMuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aID', models.IntegerField(db_column='aID', max_length=10)),
                ('uID', models.IntegerField(db_column='uID', max_length=10)),
                ('addDate', models.DateField(db_column='addDate')),
                ('addTime', models.CharField(db_column='addTime', max_length=18)),
                ('addDepartment', models.CharField(db_column='addDepartment', max_length=11)),
                ('addResult', models.CharField(db_column='addResult', max_length=100)),
                ('createAt', models.DateTimeField(db_column='createAt')),
                ('updateAt', models.DateTimeField(db_column='updateAt')),
            ],
            options={
                'db_table': 'AppointmentRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='gbk_chinese_ci', max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('effect', models.CharField(db_collation='gbk_chinese_ci', max_length=1000)),
                ('drug_usage', models.CharField(db_collation='gbk_chinese_ci', max_length=1000)),
                ('picture', models.CharField(max_length=1000)),
                ('type', models.CharField(db_collation='gbk_chinese_ci', max_length=1000)),
                ('sale', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'mywebDrug',
                'managed': True,
            },
        ),
    ]
